FROM python:3.12-slim

WORKDIR /backend

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock* ./

RUN pip install --upgrade pip
RUN pip install uv && uv sync

COPY .env ./
COPY alembic.ini ./